[workspace]

members = [
    "dpmaster-proto",
    "dpmaster-codec",
    "dpmaster-game-client-bin",
]

# https://docs.rs/color-eyre/0.5.10/color_eyre/#improving-perf-on-debug-builds
[profile.dev.package.backtrace]
opt-level = 3